apiVersion: v1
kind: Secret
metadata:
  name: artifactory-pull-secret
  namespace: default  # change to the namespace where you deploy your pods
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: BASE64_ENCODED_DOCKER_CONFIG  # Will replace with actual value in instructions
