name: aws-ecr-credentials
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start a kind cluster with containerd
        uses: helm/kind-action@v1.12.0
        with:
          cluster_name: kind-${{ github.run_id }}
          kubectl_version: "v1.32.2"
          config: ./hack/ci/containerd-cluster-conf.yaml

      - name: Build image
        run: ./hack/ci/build.sh

      - name: Set image version
        run: |
          echo "VALUE_FILE=charts/warm-metal-csi-driver/values.yaml" >> "$GITHUB_ENV"
          echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
          echo "HELM_NAME=wm-csi-integration-tests" >> "$GITHUB_ENV"
      
      # Make the mock AWS ECR credential provider executable
      - name: Set up mock credential provider
        run: |
          mkdir -p /tmp/cred-provider/bin
          cp test/integration/mock-aws-provider/ecr-login /tmp/cred-provider/bin/
          chmod +x /tmp/cred-provider/bin/ecr-login
          cp test/integration/mock-aws-provider/config.json /tmp/cred-provider/
          echo "Provider files:"
          ls -la /tmp/cred-provider/
          ls -la /tmp/cred-provider/bin/

      - name: Install the CSI Driver with credential provider
        run: |
          helm install ${HELM_NAME} charts/warm-metal-csi-driver -n kube-system \
            -f ${VALUE_FILE} \
            --set csiPlugin.image.tag=${IMAGE_TAG} \
            --set-string csiPlugin.args[0]="--image-credential-provider-config=/tmp/cred-provider/config.json" \
            --set-string csiPlugin.args[1]="--image-credential-provider-bin-dir=/tmp/cred-provider/bin" \
            --set csiPlugin.volumeMounts[0].name=cred-provider \
            --set csiPlugin.volumeMounts[0].mountPath=/tmp/cred-provider \
            --set csiPlugin.volumeMounts[0].readOnly=true \
            --set nodeplugin.volumes[0].name=cred-provider \
            --set nodeplugin.volumes[0].hostPath.path=/tmp/cred-provider \
            --set nodeplugin.volumes[0].hostPath.type=Directory \
            --wait \
            --debug

      - name: Run AWS ECR credential test
        run: |
          kubectl apply -f test/integration/manifests/ephemeral-volume-aws-ecr.yaml
          kubectl wait --for=condition=complete job/ephemeral-volume-aws-ecr --timeout=5m

      - name: Show test job logs
        if: always()
        run: |
          kubectl logs job/ephemeral-volume-aws-ecr

      - name: Uninstall the CSI Driver
        if: always()
        run: helm uninstall -n kube-system ${HELM_NAME} --wait
